version: '3'
services:
  ollama-intel-arc:
    build: .
    image: ollama-intel-arc:latest
    container_name: ollama-intel-arc
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ollama-volume:/root/.ollama
    ports:
      - 11434:11434
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui-volume:/app/backend/data
    depends_on:
      - ollama-intel-arc
    ports:
      - 3000:8080
    environment:
      - WEBUI_AUTH=False
      - ENABLE_OPENAI_API=False
      - ENABLE_OLLAMA_API=True
      - ENABLE_IMAGE_GENERATION=True
      - IMAGE_GENERATION_ENGINE=automatic1111
      - IMAGE_GENERATION_MODEL=dreamshaper_8
      - IMAGE_SIZE=400x400
      - IMAGE_STEPS=30
      - AUTOMATIC1111_BASE_URL=http://sdnext-ipex:7860/
      - AUTOMATIC1111_CFG_SCALE=9
      - AUTOMATIC1111_SAMPLER=DPM++ SDE
      - AUTOMATIC1111_SCHEDULER=Karras
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  sdnext-ipex:
    build:
      context: sdnext
      dockerfile: Dockerfile
    image: sdnext-ipex:latest
    container_name: sdnext-ipex
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 7860:7860
    volumes:
      - sdnext-app-volume:/app
      - sdnext-mnt-volume:/mnt
      - sdnext-huggingface-volume:/root/.cache/huggingface

volumes:
  ollama-volume: {}
  open-webui-volume: {}
  sdnext-app-volume: {}
  sdnext-mnt-volume: {}
  sdnext-huggingface-volume: {}
