version: "1.0"
services:
  ollama-ipex-llm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-ipex-llm
    image: ollama-ipex-llm:latest
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ollama-volume:/root/.ollama
    ports:
      - 11434:11434
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui-volume:/app/backend/data
    depends_on:
      - ollama-ipex-llm
    ports:
      - 3000:8080
    environment:
      - WEBUI_AUTH=False
      - ENABLE_OPENAI_API=False
      - ENABLE_OLLAMA_API=True
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
volumes:
  ollama-volume: {}
  open-webui-volume: {}
